# Generated by Django 4.2.1 on 2023-10-10 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Donnees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField(null=True)),
                ('date', models.CharField(max_length=25)),
                ('on_off', models.BooleanField()),
            ],
        ),
    ]
