# Generated by Django 4.2.1 on 2023-10-10 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dubstep_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='donnees',
            name='date',
            field=models.CharField(max_length=255),
        ),
    ]
