# Generated by Django 4.2.1 on 2023-10-12 11:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dubstep_app', '0002_alter_donnees_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='Temp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('temp', models.FloatField(null=True)),
                ('date', models.CharField(max_length=255)),
            ],
        ),
        migrations.RemoveField(
            model_name='donnees',
            name='temp',
        ),
    ]
