# Generated by Django 4.2.1 on 2023-10-12 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dubstep_app', '0004_donnees_topicname'),
    ]

    operations = [
        migrations.AddField(
            model_name='temp',
            name='topicname',
            field=models.CharField(default=0, max_length=255),
            preserve_default=False,
        ),
    ]
