# Generated by Django 4.2.1 on 2023-10-17 11:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dubstep_app', '0010_alter_plageshoraires_topicname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plageshoraires',
            name='plages_on_off',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
